-- Integrity constraints that Prisma's schema language cannot express.
--
-- `0001_init` is generated by `prisma migrate dev --name init` from schema.prisma and
-- creates the tables, enums, foreign keys and indexes. This migration adds the rules
-- that make incorrect data impossible rather than merely discouraged.
--
-- Every constraint here is load-bearing. If one is dropped, a specific bug becomes
-- reachable, and the comment above it says which. Nothing in this file is decoration.
--
-- Column identifiers are quoted camelCase because Prisma maps field names to column
-- names verbatim. Keep the quotes; unquoted `amountMinor` folds to `amountminor` and
-- will not resolve.

-- ---------------------------------------------------------------------- money

-- A zero or negative withdrawal is either a bug or an attempt to credit an account by
-- withdrawing a negative amount. The client-side minimum in WithdrawForm is a courtesy
-- to the reader; this is the control.
ALTER TABLE "withdrawal"
  ADD CONSTRAINT "withdrawal_amount_positive" CHECK ("amountMinor" > 0);

ALTER TABLE "commission"
  ADD CONSTRAINT "commission_amount_positive" CHECK ("amountMinor" > 0);

ALTER TABLE "partner"
  ADD CONSTRAINT "partner_minimum_nonneg" CHECK ("minimumMinor" >= 0);

-- ISO 4217 is three uppercase letters. `@db.Char(3)` fixes the length and nothing else,
-- so without this a currency of 'usd' or '   ' is storable and will not match the
-- partner's 'USD' on the composite foreign key — producing a confusing FK violation
-- instead of a clear one.
ALTER TABLE "partner"
  ADD CONSTRAINT "partner_currency_iso" CHECK ("currency" ~ '^[A-Z]{3}$');
ALTER TABLE "commission"
  ADD CONSTRAINT "commission_currency_iso" CHECK ("currency" ~ '^[A-Z]{3}$');
ALTER TABLE "withdrawal"
  ADD CONSTRAINT "withdrawal_currency_iso" CHECK ("currency" ~ '^[A-Z]{3}$');

-- ----------------------------------------------------------------- state coherence

-- A commission is CONFIRMED if and only if it has a confirmation timestamp. Without
-- this, a row can claim to be withdrawable while carrying no record of when it became
-- so — which is the first question asked in any commission dispute.
ALTER TABLE "commission"
  ADD CONSTRAINT "commission_confirmed_at_iff_confirmed"
  CHECK (("state" = 'CONFIRMED'::"commission_state") = ("confirmedAt" IS NOT NULL));

-- Billing period is `YYYY-MM`. It is concatenated into the withdrawal's display label
-- and grouped on in reporting; a free-form string there means the grouping silently
-- splits.
ALTER TABLE "commission"
  ADD CONSTRAINT "commission_period_format" CHECK ("period" ~ '^\d{4}-\d{2}$');

-- Once a withdrawal has been handed to the payout provider it must carry the
-- provider's reference. A PAID row with no reference cannot be reconciled against the
-- provider's statement, which is the whole point of holding it.
ALTER TABLE "withdrawal"
  ADD CONSTRAINT "withdrawal_provider_ref_when_moving"
  CHECK ("status"::text NOT IN ('PROCESSING', 'PAID') OR "providerRef" IS NOT NULL);

-- Retention must end after consent begins. Guards against a policy table misconfigured
-- to a negative window, which would make the purge job delete leads on arrival.
ALTER TABLE "lead"
  ADD CONSTRAINT "lead_retention_after_consent" CHECK ("retentionUntil" > "consentAt");

-- ------------------------------------------------------------- one default method

-- `isDefault` is meaningless if two rows carry it. A partial unique index expresses
-- "at most one default among a partner's live methods" exactly; a plain unique index
-- would forbid a partner from having more than one non-default method.
CREATE UNIQUE INDEX "payout_method_one_default_per_partner"
  ON "payout_method" ("partnerId")
  WHERE "isDefault" AND "archivedAt" IS NULL;

-- --------------------------------------------------------- balance query coverage
--
-- The available-balance computation runs on every wallet read and inside every
-- withdrawal transaction. It is three aggregates over one partner:
--
--   SUM("amountMinor") FROM commission WHERE "partnerId" = $1 AND state = 'CONFIRMED'
--   SUM("amountMinor") FROM commission WHERE "partnerId" = $1 AND state = 'PENDING'
--   SUM("amountMinor") FROM withdrawal WHERE "partnerId" = $1 AND status <> 'REJECTED'
--
-- These partial covering indexes let Postgres answer all three with index-only scans:
-- the predicate removes the irrelevant states from the index entirely, and INCLUDE
-- carries the summed column so the heap is never visited. See Department 20 for the
-- resulting plans.

CREATE INDEX "commission_balance_confirmed"
  ON "commission" ("partnerId") INCLUDE ("amountMinor")
  WHERE "state" = 'CONFIRMED'::"commission_state";

CREATE INDEX "commission_balance_pending"
  ON "commission" ("partnerId") INCLUDE ("amountMinor")
  WHERE "state" = 'PENDING'::"commission_state";

CREATE INDEX "withdrawal_balance_committed"
  ON "withdrawal" ("partnerId") INCLUDE ("amountMinor")
  WHERE "status" <> 'REJECTED'::"withdrawal_status";

-- --------------------------------------------------------------- reference minting
--
-- Human-readable withdrawal references (`WD-2026-000431`) are minted from a sequence,
-- not from `COUNT(*) + 1`. A count is read-then-write: two concurrent requests read
-- the same count and mint the same reference, and the unique constraint on
-- `withdrawal.reference` then fails one of them for a reason that has nothing to do
-- with what the user did. `nextval` is atomic and never returns the same value twice.
--
-- Gaps are expected and harmless: a rolled-back transaction consumes a value. A
-- reference is an identifier, not a count of anything.

CREATE SEQUENCE IF NOT EXISTS "withdrawal_reference_seq" AS bigint START WITH 1 INCREMENT BY 1;

-- ------------------------------------------------------------------- append-only
--
-- `withdrawal_event` is the record a payment dispute is settled from. A mutable audit
-- trail is not an audit trail: if a row can be edited after the fact, its evidential
-- value is zero, and the argument it was meant to end becomes unwinnable.
--
-- The trigger enforces this against every client — Prisma, psql, a migration, an ORM
-- someone adds in two years. The REVOKE below is defence in depth for the ordinary
-- application role; the trigger is the control, because it cannot be bypassed by a
-- connection that happens to be a superuser.

CREATE OR REPLACE FUNCTION "withdrawal_event_append_only"() RETURNS trigger
  LANGUAGE plpgsql AS $$
BEGIN
  RAISE EXCEPTION
    'withdrawal_event is append-only; % is not permitted. Record a new event instead.',
    TG_OP
    USING ERRCODE = 'restrict_violation';
END;
$$;

CREATE TRIGGER "withdrawal_event_no_update"
  BEFORE UPDATE ON "withdrawal_event"
  FOR EACH ROW EXECUTE FUNCTION "withdrawal_event_append_only"();

CREATE TRIGGER "withdrawal_event_no_delete"
  BEFORE DELETE ON "withdrawal_event"
  FOR EACH ROW EXECUTE FUNCTION "withdrawal_event_append_only"();

-- Defence in depth. `campus_turkey_app` is the least-privilege role the application
-- connects as; create it during environment setup (see docs/DEPLOYMENT.md) and grant
-- it only what it needs. The DO block makes this a no-op when the role does not exist,
-- so the migration is safe to run against a local database owned by a single user.
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'campus_turkey_app') THEN
    REVOKE UPDATE, DELETE ON TABLE "withdrawal_event" FROM "campus_turkey_app";
  END IF;
END;
$$;
